# Generated by Django 5.0.3 on 2024-04-23 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_vehicle_typemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_detailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Veh_regno', models.IntegerField()),
                ('Reg_date', models.DateField(max_length=8)),
                ('Tank_capacity', models.CharField(max_length=20)),
                ('Standard_mileage', models.CharField(max_length=50)),
                ('Engine_no', models.CharField(max_length=50)),
                ('Chasis_no', models.CharField(max_length=50)),
                ('No_of_tyres', models.IntegerField(max_length=4)),
                ('Fuel_Type', models.CharField(max_length=50)),
                ('Seating_capacity', models.CharField(max_length=50)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.vehicle_typemodel')),
            ],
        ),
    ]
