# Generated by Django 5.0.3 on 2024-04-26 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0012_alter_eventmodel_description_and_more'),
        ('company', '0004_alter_vehicle_detailsmodel_no_of_tyres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_PackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_Name', models.CharField(max_length=50)),
                ('Duration', models.DateField(max_length=8)),
                ('No_of_Packages', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Package_Contents', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('Insurance_Company', models.CharField(max_length=50)),
                ('Notes', models.TextField(max_length=50, null=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.stay_detailsmodel')),
                ('Stay_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.stay_categorymodel')),
            ],
        ),
    ]
