# Generated by Django 5.0.3 on 2024-04-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_tour_packagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_packagemodel',
            old_name='Name',
            new_name='Stay_Name',
        ),
    ]
