# Generated by Django 5.0.3 on 2024-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_name_tour_packagemodel_stay_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_packagemodel',
            name='Notes',
        ),
        migrations.AddField(
            model_name='tour_packagemodel',
            name='Image',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
