# Generated by Django 5.0.3 on 2024-04-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0012_alter_eventmodel_description_and_more'),
        ('company', '0007_remove_tour_packagemodel_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_packagemodel',
            name='Package_Contents',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='PilgrimcenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pilg_Name', models.CharField(max_length=40)),
                ('Pilg_Address', models.TextField(max_length=50)),
                ('Pilg_Description', models.TextField(max_length=300)),
                ('Pilg_image', models.FileField(null=True, upload_to='photos')),
                ('Pilh_link', models.CharField(max_length=50)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.districtmodel')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.locationmodel')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.countrymodel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.statemodel')),
            ],
        ),
    ]
