# Generated by Django 5.0.3 on 2024-04-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_tour_packagemodel_package_contents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilgrimcentermodel',
            old_name='Pilh_link',
            new_name='Pilg_link',
        ),
    ]
