# Generated by Django 5.0.3 on 2024-04-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0012_alter_eventmodel_description_and_more'),
        ('company', '0009_rename_pilh_link_pilgrimcentermodel_pilg_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_packagemodel',
            name='Destination',
            field=models.ManyToManyField(to='adminhome.destinationmodel'),
        ),
        migrations.AddField(
            model_name='tour_packagemodel',
            name='pilgrimcenter',
            field=models.ManyToManyField(to='company.pilgrimcentermodel'),
        ),
    ]
