# Generated by Django 5.0.3 on 2024-04-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_tour_packagemodel_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_packagemodel',
            name='Image1',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
