# Generated by Django 5.0.3 on 2024-04-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_tour_packagemodel_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_packagemodel',
            name='Duration',
            field=models.CharField(max_length=20),
        ),
    ]
