# Generated by Django 5.0.7 on 2024-08-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_tour_packagemodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrimcentermodel',
            name='Pilg_Description',
            field=models.TextField(max_length=100),
        ),
    ]
