# Generated by Django 5.0.7 on 2024-08-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_pilgrimcentermodel_pilg_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrimcentermodel',
            name='Pilg_Address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pilgrimcentermodel',
            name='Pilg_Description',
            field=models.TextField(max_length=250),
        ),
    ]
