# Generated by Django 5.0.3 on 2024-04-24 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0012_alter_eventmodel_description_and_more'),
        ('registration', '0003_itineraryreg_model_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=20)),
                ('Itineraryreg_Date', models.DateField(default=django.utils.timezone.now)),
                ('Address', models.TextField(max_length=200)),
                ('ZIP', models.IntegerField()),
                ('Mobno', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Status', models.CharField(default='INACTIVE', max_length=10)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.countrymodel')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.locationmodel')),
                ('Login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.statemodel')),
            ],
        ),
    ]
