# Generated by Django 5.0.3 on 2024-04-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_itinerary_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itineraryreg_Model',
        ),
    ]
