# Generated by Django 5.0.3 on 2024-04-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminhome', '0013_destinationmodel_image'),
        ('company', '0012_alter_tour_packagemodel_duration'),
        ('registration', '0005_delete_itineraryreg_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Street_Address', models.TextField(max_length=200)),
                ('Mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('Profession', models.CharField(max_length=50)),
                ('Organization', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('ZIP', models.IntegerField()),
                ('No_of_Persons', models.CharField(max_length=50)),
                ('Adults', models.IntegerField()),
                ('Children', models.IntegerField()),
                ('Reserv_Date', models.DateField(max_length=8)),
                ('Country_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.countrymodel')),
                ('Itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.itinerary_model')),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.tour_packagemodel')),
                ('State_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.statemodel')),
            ],
        ),
    ]
