# Generated by Django 5.0.3 on 2024-05-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0002_alter_reservation_model_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerarychild_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itin_Child_Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Mstatus', models.CharField(max_length=20)),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Itinerary.reservation_model')),
            ],
        ),
    ]
