# Generated by Django 5.0.3 on 2024-05-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0003_itinerarychild_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_model',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation_model',
            name='Gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
