# Generated by Django 5.0.3 on 2024-05-03 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0004_reservation_model_age_reservation_model_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_Date', models.DateField(max_length=8)),
                ('Mode_Payment', models.CharField(max_length=20)),
                ('dd_chq_no', models.IntegerField()),
                ('card_type', models.CharField(max_length=20)),
                ('Card_Holder_Name', models.CharField(max_length=20)),
                ('card_no', models.IntegerField()),
                ('cvv_no', models.IntegerField()),
                ('exp_date', models.DateField(max_length=8)),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Itinerary.reservation_model')),
            ],
        ),
    ]
