# Generated by Django 5.0.3 on 2024-05-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0005_payment_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_model',
            old_name='dd_chq_no',
            new_name='Amount',
        ),
    ]
