# Generated by Django 5.0.3 on 2024-05-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0006_rename_dd_chq_no_payment_model_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerarychild_model',
            old_name='Itin_Child_Name',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='itinerarychild_model',
            old_name='Mstatus',
            new_name='ItineraryName',
        ),
    ]
