# Generated by Django 5.0.3 on 2024-05-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0007_rename_itin_child_name_itinerarychild_model_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='Reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Itinerary.reservation_model'),
        ),
    ]
