# Generated by Django 5.0.3 on 2024-05-07 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0008_alter_payment_model_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_model',
            name='Mode_Payment',
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='Trans_Date',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='exp_date',
            field=models.CharField(max_length=8),
        ),
    ]
