# Generated by Django 5.0.3 on 2024-05-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0009_remove_payment_model_mode_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='card_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation_model',
            name='Organization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation_model',
            name='Profession',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
