# Generated by Django 5.0.3 on 2024-05-07 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0010_alter_payment_model_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='Trans_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
