# Generated by Django 5.0.3 on 2024-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0011_alter_payment_model_trans_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_model',
            name='status',
            field=models.CharField(default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='card_type',
            field=models.CharField(choices=[('select', 'SELECT'), ('credit', 'CREDIT'), ('debit', 'DEBIT'), ('mastercard', 'MASTERCARD')], default='SELECT', max_length=20),
        ),
    ]
