# Generated by Django 5.0.1 on 2024-05-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0012_payment_model_status_alter_payment_model_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_model',
            name='card_type',
        ),
    ]
