# Generated by Django 5.0.1 on 2024-05-28 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0013_remove_payment_model_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_model',
            name='Reserv_Date',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
        ),
    ]
