# Generated by Django 5.0.7 on 2024-08-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0016_feedbackmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='Message',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
