# Generated by Django 5.0.3 on 2024-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0006_alter_destinationmodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay_categoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stay_type', models.CharField(max_length=20, null=True)),
                ('photo', models.FileField(blank=True, upload_to='photos')),
            ],
            options={
                'db_table': 'stay_cat_table',
            },
        ),
    ]
