# Generated by Django 5.0.3 on 2024-04-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0007_stay_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay_DetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=50)),
                ('Tarrif_range', models.IntegerField()),
                ('Lphone', models.BigIntegerField()),
                ('mobno', models.BigIntegerField()),
                ('fax', models.BigIntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('images', models.FileField(blank=True, upload_to='photos')),
                ('link', models.CharField(max_length=50)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.districtmodel')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.locationmodel')),
                ('Stay_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.stay_categorymodel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.statemodel')),
            ],
        ),
    ]
