# Generated by Django 5.0.3 on 2024-04-22 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0009_delete_stay_detailsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=20, null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
                ('Importance', models.CharField(max_length=50, null=True)),
                ('Date', models.DateField(max_length=8)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.locationmodel')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.districtmodel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.statemodel')),
            ],
        ),
    ]
