# Generated by Django 5.0.3 on 2024-04-22 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0010_eventmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.countrymodel'),
        ),
    ]
