# Generated by Django 5.0.3 on 2024-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0012_alter_eventmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='photos'),
        ),
    ]
