# Generated by Django 5.0.1 on 2024-05-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0013_destinationmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtmodel',
            name='Description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
