# Generated by Django 5.0.1 on 2024-05-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0014_alter_districtmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='Description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
