# Generated by Django 5.0.1 on 2024-05-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0015_alter_locationmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtmodel',
            name='Description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
