# Generated by Django 5.0.1 on 2024-06-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0016_alter_districtmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='Description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
