# Generated by Django 5.0.6 on 2024-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0017_alter_locationmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_catmodel',
            name='Destination_cat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='Destination',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
