# Generated by Django 5.0.7 on 2024-08-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0018_alter_destination_catmodel_destination_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='Location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
