# Generated by Django 5.0.7 on 2024-08-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0019_alter_locationmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='Event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
